name: .NET Core 6 WebApplication Build, Test and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Install Dependencies
      run: dotnet restore
    - name: Build and Test
      run: |
        dotnet build
        dotnet test
    - name: Scan for Security Risks
      uses: github/codeql-action/analyze@v1
    - name: Deploy
      run: dotnet publish -o /deployment
      env:
        PUBLISH_PATH: /deployment
        DOTNET_ROOT: ${{ env.HOME }}/.dotnet
